version: '3.8'

services:
  loyalty:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: loyalty-api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: loyalty
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: mq
      RABBITMQ_PORT: 5672
      AUTH_BASE_URL: http://keycloak:8080
      KEYCLOAK_ISSUER_URL: http://keycloak:8080/realms/loyalty
      REDIS_URL: 'redis://redis:6379'
    env_file:
      - backend/.env
    depends_on:
      - postgres
      - mq
      - redis
      - keycloak
    restart: always
    command: sh -c "npm install && npm install -g knex && knex migrate:latest && npm start"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: loyalty
    ports:
      - "5432:5432"

  authdb:
    image: postgres:15
    container_name: authdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    ports:
      - "5434:5432"
  
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: keycloak
    ports:
    - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev","--db","postgres","--db-url","jdbc:postgresql://authdb:5432/keycloak","--db-username","postgres","--db-password","password","--import-realm"]
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    depends_on:
      - authdb
  
  mq:
    image: rabbitmq:3
    container_name: mq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest # just making the default values explicit
    ports: 
      - 5672:5672
      - 8089:8080 # Management is available on port 8089 on host machine

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - 6379:6379
