version: '3.8'

services:
  nodejs-backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: loyalty-api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: loyalty
    env_file:
      - backend/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: loyalty
    ports:
      - "5432:5432"
