services:
  loyalty:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loyalty-api
    ports:
      - "3000:3000"
    environment:
      DB_CLIENT: 'pg'
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: loyalty
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: mq
      RABBITMQ_PORT: 5672
      AUTH_BASE_URL: http://keycloak:8080
      KEYCLOAK_ISSUER_URL: http://keycloak:8080/realms/loyalty
      REDIS_URL: 'redis://redis:6379'
      SALESFORCE_AUTH_TYPE: username-password
      PUB_SUB_ENDPOINT: api.pubsub.salesforce.com:7443
      USE_LOCAL_CACHE: false
      USE_IN_MEMORY_DB: false
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
      mq:
        condition: service_started
      redis:
        condition: service_started
      keycloak:
        condition: service_healthy
    command: sh -c "npm install && npm install -g knex && knex migrate:latest && npm start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 60s
      retries: 5

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: loyalty
    ports:
      - "5432:5432"

  authdb:
    image: postgres:15
    container_name: authdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    ports:
      - "5434:5432"
  
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: keycloak
    ports:
    - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
    command: ["start-dev","--db","postgres","--http-port","8080","--db-url","jdbc:postgresql://authdb:5432/keycloak","--db-username","postgres","--db-password","password","--import-realm"]
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    depends_on:
      - authdb
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/localhost/8080' # https://stackoverflow.com/a/77638224/821110
      timeout: 30s
      retries: 5
  
  mq:
    image: rabbitmq:3
    container_name: mq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest # just making the default values explicit
    ports: 
      - 5672:5672

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - 6379:6379